name = "kas-kita"
main = "worker.js"
compatibility_date = "2025-01-01"

# ---------- D1 Database ----------
# Buat dulu dengan: wrangler d1 create kas-kita-db
# Lalu isi database_id di bawah ini dengan hasilnya
[[d1_databases]]
binding = "DB"
database_name = "kas-kita-db"
database_id = "e827123b-84f9-462f-9848-51393430147d"

# ---------- Variabel biasa (boleh dilihat publik) ----------
[vars]
APP_URL = "https://kas-kita.danangpandanu02.workers.dev/"
MAIL_FROM = "noreply@contoh-domain.com"

# ---------- Static assets (frontend PWA) ----------
[assets]
directory = "./public"
binding = "ASSETS"

# ---------- Secrets (JANGAN ditulis di sini, isi lewat CLI) ----------
# wrangler secret put JWT_SECRET
# wrangler secret put MAILCHANNELS_API_KEY
